SWM-REPL/gifthub-was

src/main/java/org/swmaestro/repl/gifthub/auth/entity/CustomUserDetails.java
src/main/java/org/swmaestro/repl/gifthub/auth/service/JpaUserDetailsService.java
src/main/java/org/swmaestro/repl/gifthub/config/SecurityConfig.java
src/main/java/org/swmaestro/repl/gifthub/util/JwtUtil.java
src/main/java/org/swmaestro/repl/gifthub/util/filter/JwtAuthenticationFilter.java

feat: implement JwtAuthenticationFilter

---

src/main/java/org/swmaestro/repl/gifthub/auth/controller/AuthController.java
src/main/java/org/swmaestro/repl/gifthub/auth/service/AuthService.java
src/main/java/org/swmaestro/repl/gifthub/auth/service/AuthServiceImpl.java
src/main/java/org/swmaestro/repl/gifthub/auth/service/MemberServiceImpl.java
src/main/java/org/swmaestro/repl/gifthub/config/SecurityConfig.java
src/test/java/org/swmaestro/repl/gifthub/auth/controller/AuthControllerTest.java
src/test/java/org/swmaestro/repl/gifthub/auth/service/AuthServiceTest.java
src/test/java/org/swmaestro/repl/gifthub/auth/service/MemberServiceTest.java

- #16 반영
- AuthController & AuthServiceTest 수정
- 로그인 로직에 예외 처리 추가

Feat/GH-100-Login API Exception Handling

---

.github/workflows/deploy.yml

Github Actions로 빌드하고 빌드한 파일을 AWS에 복사해서 올리도록 작성했어요

chore: Create deploy.yml

---

src/main/java/org/swmaestro/repl/gifthub/auth/service/MemberServiceImpl.java

기존 사용자가 닉네임 길이를 DB에서 저장할 수 있는 글자 수 보다 길게 입력했을 경우 500 에러가 발생하여 예외 처리가 필요하였음
400 에러로 예외 처리 환료
프론트에서 발견 및 수정 요청한 사항입니다.

Add nickname exception handling

---

src/main/java/org/swmaestro/repl/gifthub/vouchers/service/StorageService.java
src/main/java/org/swmaestro/repl/gifthub/vouchers/service/VoucherService.java

프론트엔드에서 voucher의 기본 이미지를 등록해주길 원하였음
image_url을 등록하지 않더라도 기본 이미지를 DB에 저장하도록 수정하였음
- 현재 S3의 URL이 `https`가 아닌 `http`로 동작하고 있음
- S3 저장소 버킷 변경에 따른 일부 함수 로직이 변경되었음

feat: implement get-default-voucher-image method

---

src/main/java/org/swmaestro/repl/gifthub/GifthubApplication.java
src/main/java/org/swmaestro/repl/gifthub/config/SwaggerConfig.java

Swagger는 기본적으로 요청을 http으로 보내기 때문에 https로 수정해야 했습니다.
- `@OpenAPIDefinition`에 `servers`를 추가했습니다. 
❗️어떤 서버를 호출할 건지 선택해주어야 합니다.
❗️`application.yml` 업데이트하여 `1password`에 업로드 하였습니다.

Apply Https to Swagger

---

src/main/java/org/swmaestro/repl/gifthub/vouchers/controller/VoucherController.java
src/main/java/org/swmaestro/repl/gifthub/vouchers/service/VoucherService.java

`voucher` 수정 시 성공 메세지를 수정하고자 하였습니다.
변경한 `voucher` 정보를 저장하고자 하였습니다.

Save update of voucher and Modify ok status message

---

src/main/java/org/swmaestro/repl/gifthub/auth/controller/AuthController.java
src/main/java/org/swmaestro/repl/gifthub/auth/dto/AppleDto.java
src/main/java/org/swmaestro/repl/gifthub/auth/dto/GoogleDto.java
src/main/java/org/swmaestro/repl/gifthub/auth/dto/KakaoDto.java
src/main/java/org/swmaestro/repl/gifthub/auth/dto/NaverDto.java
src/main/java/org/swmaestro/repl/gifthub/auth/entity/OAuth.java
src/main/java/org/swmaestro/repl/gifthub/auth/repository/OAuthRepository.java
src/main/java/org/swmaestro/repl/gifthub/auth/service/AppleService.java
src/main/java/org/swmaestro/repl/gifthub/auth/service/AuthServiceImpl.java
src/main/java/org/swmaestro/repl/gifthub/auth/service/GoogleService.java
src/main/java/org/swmaestro/repl/gifthub/auth/service/KakaoService.java
src/main/java/org/swmaestro/repl/gifthub/auth/service/NaverService.java
src/main/java/org/swmaestro/repl/gifthub/auth/service/OAuthService.java
src/main/java/org/swmaestro/repl/gifthub/auth/type/OAuthPlatform.java
src/main/java/org/swmaestro/repl/gifthub/vouchers/service/VoucherService.java
src/test/java/org/swmaestro/repl/gifthub/auth/controller/AuthControllerTest.java
src/test/java/org/swmaestro/repl/gifthub/auth/service/AuthServiceTest.java

사용자의 OAuth 정보를 저장하기 위해
OAuth 테이블을 분리하고, 이에 따른 값 저장
- Apple 로그인 제외 모두 테스트 완료하였습니다.
- AuthService 테스트는 코드 변경에 따라 지나친 작업 시간 소요가 예상되어 전부 주석처리하였습니다.

Add oauth-info logic

---

.github/workflows/on_pull_request.yml
.github/workflows/on_push.yml
Dockerfile
docker-compose.yml

`on_pull_request` 내 에서의 docker build & push 작업을 `on_push`로 옮기고자 하였습니다.
`github_sha`값을 이용하여 이미지의 버전관리를 가능케 하고자 하였습니다. 
❗️gradle build 작업을 Dockerfile 내에서 하여 docker image 빌드를 하였습니다. 
~~❗️application.yml파일을 호스트 서버안에 미리 생성해두고, docker volume을 이용해 컨테이너 내의 경로와 mount 하여 secret key file을 관리하고자 하였습니다.~~
💧Docker volume이 해결되지 않아, 더이상 시간을 쓰기가 어려워 기존처럼 이미지 안에 application.yml이 들어간 방식으로 진행했습니다. 참고자료 첨부드립니다.
1. docker volume 확인
2. volume 안에 application.yml 파일 확인
3. 에러 발생
4. 마운트 안됨

Change docker build and push

---

src/main/java/org/swmaestro/repl/gifthub/vouchers/controller/VoucherController.java
src/test/java/org/swmaestro/repl/gifthub/vouchers/controller/VoucherControllerTest.java

FE 요청으로 Voucher 조회 시 query string을 member_id에서 user_id로 변경
.
.

Change member_id to user_id In voucher-list api

---

.github/workflows/on_push.yml
docker-compose.yml

Continuous Deployment가 제대로 작동하지 않았습니다.
너무나도 답답한 나머지, 직접 실험해보았습니다.
1. `docker run` 명령어로 실행 시, 기존 컨테이너가 계속 실행되고 새로운 컨테이너는 생성만 되고 실행되지 않았습니다.(기존 컨테이너가 8080포트를 사용하고 있어서로 추정)
2. 서버에 `docker-compose`가 설치되어 있어야 합니다. (기존에 `docker-compose` 명령어로 잘 실행되었기 때문에 설치되어 있을 것이라 생각)
3. 기존에 `docker-compose up`에서 `docker run`으로 바꾼 이유가 환경변수가 제대로 작동하지 않았기 때문인데, 순서를 바꾸니까 작동합니다.
🤔 왜 docker-compose로 실행하면 같은 포트를 사용하고 있는 컨테이너가 자동으로 죽고, 새로운 container가 점유하게 되는 걸까요?
docker-compose의 작동방식이 궁금해졌습니다..

Run with docker-compose

---

src/main/java/org/swmaestro/repl/gifthub/auth/controller/AuthController.java
src/main/java/org/swmaestro/repl/gifthub/auth/service/AppleService.java
src/main/java/org/swmaestro/repl/gifthub/auth/service/AuthServiceImpl.java
src/main/java/org/swmaestro/repl/gifthub/auth/service/GoogleService.java
src/main/java/org/swmaestro/repl/gifthub/auth/service/KakaoService.java
src/main/java/org/swmaestro/repl/gifthub/auth/service/MemberServiceImpl.java
src/main/java/org/swmaestro/repl/gifthub/auth/service/NaverService.java
src/main/java/org/swmaestro/repl/gifthub/auth/service/RefreshTokenService.java
src/main/java/org/swmaestro/repl/gifthub/util/JwtProvider.java
src/test/java/org/swmaestro/repl/gifthub/auth/controller/AuthControllerTest.java
src/test/java/org/swmaestro/repl/gifthub/util/JwtUtilTest.java

클라이언트 요청에 따라 JWT Payload에 userId를 추가하였습니다.
claim 메소드를 이용해 `userId` claim을 만들고 value로 해당 user의 userId를 넣었습니다.
❗️commit message tag를 `feat`으로 했어야 했는데 `fix`로 하였습니다. 다음부터 주의하겠습니다🥲

Add user-id in JWT Payload

---

src/main/java/org/swmaestro/repl/gifthub/vouchers/service/VoucherService.java

DB에서 관리하고 있는 브랜드 및 상품에 대해서만 서비스 하기
사용자가 입력한 브랜드 및 상품이 존재하지 않을 경우 exception 처리
.

Add exception handling for brand & product

---

src/main/java/org/swmaestro/repl/gifthub/auth/controller/AuthController.java
src/main/java/org/swmaestro/repl/gifthub/auth/controller/UserController.java
src/main/java/org/swmaestro/repl/gifthub/notifications/controller/NotificationController.java
src/main/java/org/swmaestro/repl/gifthub/vouchers/controller/BrandController.java
src/main/java/org/swmaestro/repl/gifthub/vouchers/controller/ProductController.java
src/main/java/org/swmaestro/repl/gifthub/vouchers/controller/VoucherController.java
src/main/java/org/swmaestro/repl/gifthub/vouchers/service/VoucherService.java

FE 요청에 따른 API 명세서 구체화
API별 여러 예상 응답을 swagger에 추가
FE 요청에 따라 `400(4XX-X)` 형식으로 처리하였습니다.

Add multiple swagger-response

---

src/main/java/org/swmaestro/repl/gifthub/vouchers/controller/VoucherController.java
src/main/java/org/swmaestro/repl/gifthub/vouchers/entity/Voucher.java
src/main/java/org/swmaestro/repl/gifthub/vouchers/service/VoucherService.java
src/test/java/org/swmaestro/repl/gifthub/vouchers/controller/VoucherControllerTest.java

사용자가 기프티콘 삭제를 선택하였을 때 사용하기 위한 API 구현 필요
DB의 delete_at 컬럼을 현재 시간으로 수정함으로써 `soft-delete` 구현
없음

Implement voucher-delete API

---

src/main/java/org/swmaestro/repl/gifthub/vouchers/dto/VoucherUpdateRequestDto.java
src/main/java/org/swmaestro/repl/gifthub/vouchers/entity/Voucher.java
src/main/java/org/swmaestro/repl/gifthub/vouchers/service/VoucherService.java

기프티콘 정보 수정 시 잔액이 수정되지 않는 오류 발견
DTO에 잔액 필드 추가, 기프티콘 등록 시 기본 잔액 입력
없음

Add balance field to VoucherUpdateRequestDto

---

src/main/java/org/swmaestro/repl/gifthub/vouchers/service/VoucherService.java

voucher 목록 전체 조회 시 삭제된 기프티콘도 조회가 가능하였음
삭제된 기프티콘은 조회되지 않도록 필터링
FE 요청사항입니다.

Modify deleted vouchers to not be searchable

---

src/main/java/org/swmaestro/repl/gifthub/vouchers/dto/VoucherReadResponseDto.java
src/main/java/org/swmaestro/repl/gifthub/vouchers/repository/BrandRepository.java
src/main/java/org/swmaestro/repl/gifthub/vouchers/repository/ProductRepository.java
src/main/java/org/swmaestro/repl/gifthub/vouchers/service/BrandService.java
src/main/java/org/swmaestro/repl/gifthub/vouchers/service/ProductService.java
src/main/java/org/swmaestro/repl/gifthub/vouchers/service/StorageService.java
src/main/java/org/swmaestro/repl/gifthub/vouchers/service/VoucherService.java

기프티콘을 저장할 때, `image_url`이 없을 경우 오류가 발생하고 있었음
기프티콘 조회 시 `image_url`도 조회할 수 있도록 DTO 수정
.

Add image_url to voucher-read-dto

---

src/main/java/org/swmaestro/repl/gifthub/auth/entity/DeviceToken.java
src/main/java/org/swmaestro/repl/gifthub/auth/service/DeviceTokenService.java
src/main/java/org/swmaestro/repl/gifthub/notifications/controller/NotificationController.java
src/main/java/org/swmaestro/repl/gifthub/notifications/dto/DeviceTokenSaveRequestDto.java
src/main/java/org/swmaestro/repl/gifthub/notifications/service/NotificationService.java
src/test/java/org/swmaestro/repl/gifthub/notifications/controller/NotificationControllerTest.java

git status### PR Type
FE에서 Device 토큰 저장 요청할 수 있는 API 개발 요청
해당 API 구현

Implment device-token save api

---

.github/workflows/on_pull_request.yml
.github/workflows/on_push.yml
.gitignore
build.gradle
src/main/java/org/swmaestro/repl/gifthub/GifthubApplication.java
src/main/java/org/swmaestro/repl/gifthub/auth/entity/DeviceToken.java
src/main/java/org/swmaestro/repl/gifthub/auth/service/DeviceTokenService.java
src/main/java/org/swmaestro/repl/gifthub/config/FCMConfig.java
src/main/java/org/swmaestro/repl/gifthub/notifications/controller/NotificationController.java
src/main/java/org/swmaestro/repl/gifthub/notifications/dto/FCMNotificationRequestDto.java
src/main/java/org/swmaestro/repl/gifthub/notifications/service/FCMNotificationService.java
src/main/java/org/swmaestro/repl/gifthub/notifications/service/ScheduledTasks.java
src/main/java/org/swmaestro/repl/gifthub/util/BaseTimeEntity.java
src/main/java/org/swmaestro/repl/gifthub/vouchers/service/VoucherService.java

…ature/GH-230-push-noti### PR Type
사용자의 기프티콘 유효 기간이 얼마 남지 않았을 경우 Push 알림을 통해 경고를 주도록 하는 기능을 개발하려 함
- Device 토큰을 DB에 저장
- FCM을 통한 사용자 디바이스에 Push 알림 전송 기능 구현
- `@Scheduled` 어노테이션을 통해 주기적으로 푸시 알림 전송
- `@Scheduled` 어노테이션을 통해 주기적으로 디바이스 토큰 관리
- 자잘한 로직들이 수정된 게 많은 거 같아요. 크게 어려운 개념은 없어서 가볍게 보셔도 좋을 것 같습니다!
- 참고 자료
- [FCM 도입 시 고려 사항](https://seungwoolog.tistory.com/88)
- [SpringBoot - FCM 푸시 알림 전송 로직 구현](https://kbwplace.tistory.com/179)

chore: add firebase dependency

---

src/main/java/org/swmaestro/repl/gifthub/notifications/dto/FCMNotificationRequestDto.java
src/main/java/org/swmaestro/repl/gifthub/notifications/service/FCMNotificationService.java
src/main/java/org/swmaestro/repl/gifthub/notifications/service/NotificationService.java
src/main/java/org/swmaestro/repl/gifthub/notifications/service/ScheduledTasks.java
src/main/java/org/swmaestro/repl/gifthub/vouchers/service/VoucherService.java

Push 알림 전송 내역 추적의 필요성을 느낌
DB의 Notifcation 테이블을 통해 알림 전송 내역 저장 및 push 알림 전송 시 `notification_id` 전송
없음

Implement save notification logic

---

src/main/java/org/swmaestro/repl/gifthub/auth/service/KakaoService.java
src/main/java/org/swmaestro/repl/gifthub/config/SecurityConfig.java
src/main/java/org/swmaestro/repl/gifthub/notifications/controller/NotificationController.java
src/main/java/org/swmaestro/repl/gifthub/notifications/dto/NoticeNotificationDto.java
src/main/java/org/swmaestro/repl/gifthub/notifications/entity/Notification.java
src/main/java/org/swmaestro/repl/gifthub/notifications/service/FCMNotificationService.java
src/main/java/org/swmaestro/repl/gifthub/notifications/service/ScheduledTasks.java

fix: modify send expiration notification logic

---

src/main/java/org/swmaestro/repl/gifthub/auth/controller/AuthController.java
src/main/java/org/swmaestro/repl/gifthub/auth/dto/TokenDto.java
src/main/java/org/swmaestro/repl/gifthub/auth/service/KakaoService.java
src/test/java/org/swmaestro/repl/gifthub/auth/controller/AuthControllerTest.java

카카오 로그인을 도입하기 위한 검수 과정
카카오 토큰 받아오기 로직 삭제
- .

Modify kakao login logic

---

src/main/java/org/swmaestro/repl/gifthub/auth/controller/AuthController.java
src/main/java/org/swmaestro/repl/gifthub/auth/service/NaverService.java
src/test/java/org/swmaestro/repl/gifthub/auth/controller/AuthControllerTest.java

MVP 2.0을 위한 Naver OAuth 문제 해결
OAuth 요청 로직 FE와 분배 및 코드 수정
.

Modify Naver OAuth Logic

---

src/main/java/org/swmaestro/repl/gifthub/auth/controller/AuthController.java
src/main/java/org/swmaestro/repl/gifthub/auth/dto/ApplePublicKeyResponseDto.java
src/main/java/org/swmaestro/repl/gifthub/auth/dto/AppleTokenDto.java
src/main/java/org/swmaestro/repl/gifthub/auth/repository/OAuthRepository.java
src/main/java/org/swmaestro/repl/gifthub/auth/service/AppleService.java
src/main/java/org/swmaestro/repl/gifthub/auth/service/OAuthService.java
src/test/java/org/swmaestro/repl/gifthub/auth/controller/AuthControllerTest.java

MVP 2.0 개발을 위한 Apple OAuth 도입 필요
기존 Apple OAuth 로직 수정 및 에러 해결
- Request Body 예시는 Postman의 `GiftHub/Auth/애플 로그인`을 참고바랍니다.

Modify Apple OAuth API

---

src/main/java/org/swmaestro/repl/gifthub/vouchers/dto/VoucherReadResponseDto.java

기타 브랜드의 기프티콘 조회 시 에러 발생
dto의 price, balance의 타입을 int -> Integer로 변경(null 허용)
^^

fix: modify type to price, balance

---

src/main/java/org/swmaestro/repl/gifthub/auth/controller/UserController.java
src/main/java/org/swmaestro/repl/gifthub/auth/service/MemberService.java
src/test/java/org/swmaestro/repl/gifthub/auth/controller/UserControllerTest.java

사용자가 하나의 계정에 여러 OAuth 계정을 연동하는 기능 필요
사용자가 하나의 계정에 여러 OAuth 계정을 연동하는 기능 구현
없음

Implement create oauth-info API

---

src/main/java/org/swmaestro/repl/gifthub/auth/service/DeviceTokenService.java
src/main/java/org/swmaestro/repl/gifthub/notifications/controller/NotificationController.java
src/main/java/org/swmaestro/repl/gifthub/notifications/dto/DeviceTokenRequestDto.java
src/main/java/org/swmaestro/repl/gifthub/notifications/service/NotificationService.java
src/test/java/org/swmaestro/repl/gifthub/notifications/controller/NotificationControllerTest.java

FE의 Device 토큰 삭제 API 구현 요청
Device 토큰 삭제 API 구현
없음

Implement delete device-token API

---

src/main/java/org/swmaestro/repl/gifthub/auth/config/AuthConfig.java
src/main/java/org/swmaestro/repl/gifthub/auth/controller/AuthController.java
src/main/java/org/swmaestro/repl/gifthub/auth/service/AuthService.java
src/main/java/org/swmaestro/repl/gifthub/auth/service/KakaoService.java

FE와 OAuth 연동 확인을 위한 협업
Auth 로직 버그 해결
없음

Modify Auth Logic

---

src/main/java/org/swmaestro/repl/gifthub/auth/entity/OAuth.java

마이그레이션 작업 중 기존에 미처 수정하지 못했던 컬럼명 발견
- 컬럼명 변경
- DB 마이그레이션 작업 완료하였습니다.

Fix column-name

---

src/main/java/org/swmaestro/repl/gifthub/auth/service/UserService.java

- Authorization 헤더에 토큰을 보낼 경우 오류 발생
- load-user 시 null 값을 보내고 있었음 => 수정 완료
- 지난 PR에서 해결을 했었는데 Conflict 및 브랜치 명을 변경하는 과정에서 누락된 것 같습니다. 죄송합니다 ㅠㅠ

Modify load-user logic

---

src/main/java/org/swmaestro/repl/gifthub/GifthubApplication.java
src/main/java/org/swmaestro/repl/gifthub/auth/controller/UserController.java

- 비회원이 사용자 정보 수정 불가능하도록 하기 위함
- `@PreAuthorize` 어노테이션 설정
- 별도 Test API로 테스트 완료하였음

Set user-update API access permissions

---

src/main/java/org/swmaestro/repl/gifthub/auth/service/UserService.java

- 회원 탈퇴 시 500에러 발생
- deleted_at 컬럼의 null 체크 오류 수정
- 없음

Fixed user delete bug

---

src/main/java/org/swmaestro/repl/gifthub/auth/service/UserService.java

- 탈퇴된 회원에 대한 정보 및 기프티콘 조회 시 조회가 되는 이슈 발생
- deleted_at 로직 수정
- 없음

Modify member-read logic

---

src/main/java/org/swmaestro/repl/gifthub/auth/service/AuthService.java

- 탈퇴된 회원에 대한 로그아웃 처리 시 오류 발생
- deleted_at 로직 수정
- 없음

Modify member-read logic to sign-out

---

src/main/java/org/swmaestro/repl/gifthub/auth/service/KakaoService.java

카카오 정보 저장 불러오기가 잘 안됨
json 구조 확인 후 변경

Modify kakao userinfo json field

---

src/main/java/org/swmaestro/repl/gifthub/auth/config/AuthConfig.java
src/main/java/org/swmaestro/repl/gifthub/auth/controller/AuthController.java
src/main/java/org/swmaestro/repl/gifthub/auth/service/AuthService.java
src/main/java/org/swmaestro/repl/gifthub/auth/service/KakaoService.java
src/main/java/org/swmaestro/repl/gifthub/auth/service/OAuthService.java

- FE에서 제시한 에러 해결
- kakao OAuth 로직 수정
- default value(password, role) 설정
- OAuthService 리팩토링
- .

Modify kakao-sign-in logic

---

src/main/java/org/swmaestro/repl/gifthub/notifications/service/NotificationService.java

일부 notification get 요청 시 500 에러 발생 
기프티콘 등록 실패 알림의 경우, voucher가 null 이 들어가서 발생 -> 예외 처리

Modify notification map to dto when voucher is null

---

src/main/java/org/swmaestro/repl/gifthub/auth/service/UserService.java

- 삭제된 회원에 대한 리소스 접근 시 404 출력
- 401로 변경
- 없음

Modify get user logic

---

src/main/java/org/swmaestro/repl/gifthub/giftcard/entity/Giftcard.java
src/main/java/org/swmaestro/repl/gifthub/giftcard/repository/GiftcardRepository.java
src/main/java/org/swmaestro/repl/gifthub/giftcard/service/GiftcardService.java
src/main/java/org/swmaestro/repl/gifthub/vouchers/controller/VoucherController.java
src/main/java/org/swmaestro/repl/gifthub/vouchers/dto/VoucherShareRequestDto.java
src/main/java/org/swmaestro/repl/gifthub/vouchers/dto/VoucherShareResponseDto.java
src/main/java/org/swmaestro/repl/gifthub/vouchers/service/VoucherService.java
src/test/java/org/swmaestro/repl/gifthub/vouchers/controller/VoucherControllerTest.java

Implement Voucher Share Request API

---

src/main/java/org/swmaestro/repl/gifthub/auth/controller/UserController.java
src/main/java/org/swmaestro/repl/gifthub/auth/dto/OAuthUserInfoDto.java
src/main/java/org/swmaestro/repl/gifthub/auth/dto/UserDeleteResponseDto.java
src/main/java/org/swmaestro/repl/gifthub/auth/dto/UserInfoResponseDto.java
src/main/java/org/swmaestro/repl/gifthub/auth/dto/UserReadResponseDto.java
src/main/java/org/swmaestro/repl/gifthub/auth/dto/UserUpdateRequestDto.java
src/main/java/org/swmaestro/repl/gifthub/auth/dto/UserUpdateResponseDto.java
src/main/java/org/swmaestro/repl/gifthub/auth/repository/OAuthRepository.java
src/main/java/org/swmaestro/repl/gifthub/auth/service/DeviceTokenService.java
src/main/java/org/swmaestro/repl/gifthub/auth/service/OAuthService.java
src/main/java/org/swmaestro/repl/gifthub/auth/service/UserService.java
src/test/java/org/swmaestro/repl/gifthub/auth/controller/UserControllerTest.java

마이페이지에 들어갈 내 회원 정보가 필요함
내 정보 조회 API 구현

Implement My Information Read API

---

src/main/java/org/swmaestro/repl/gifthub/vouchers/controller/VoucherController.java

- 비회원은 `공유하기` 기능을 사용할 수 없도록 하고자 함
- `@PreAuthorize` 어노테이션을 통해 사용자 권한을 통해 접근 관리
- X

Set available access to role from

---

src/main/java/org/swmaestro/repl/gifthub/auth/service/DeviceTokenService.java

동일한 기기, 기존 계정과 다른 계정으로 로그인 시, 디바이스 토큰 업데이트가 기존 회원 토큰으로 저장되고 있음
디바이스 토큰 수정 시, 회원도 같이 수정되도록 함

Devicetoken User update when voucher updated

---

src/main/java/org/swmaestro/repl/gifthub/auth/controller/AuthController.java
src/main/java/org/swmaestro/repl/gifthub/auth/service/AuthService.java
src/main/java/org/swmaestro/repl/gifthub/auth/type/Role.java
src/main/java/org/swmaestro/repl/gifthub/config/SecurityConfig.java
src/test/java/org/swmaestro/repl/gifthub/auth/controller/AuthControllerTest.java

- 서비스 사용자를 확보하기 위한 방안 모색
- 비회원도 서비스를 이용할 수 있도록 하기 위해 비회원 계정 생성 API 구현
- 없음

Implement anonymous sign-up API

---

src/main/java/org/swmaestro/repl/gifthub/auth/type/Role.java
src/main/java/org/swmaestro/repl/gifthub/giftcard/entity/Giftcard.java
src/main/java/org/swmaestro/repl/gifthub/giftcard/service/GiftcardService.java

- 기존에는 무차별 비밀번호 대입 공격을 통해 10000번 시도 시 비밀번호를 알아내서 공유한 기프티콘을 탈취할 수 있었음
- 비밀번호 입력 횟수를 10회로 제한
- 횟수 초과 시 해당 링크 만료 처리
- 없음

Ser invalid password count limit 

---

src/main/java/org/swmaestro/repl/gifthub/auth/service/UserService.java

다중 기기 로그인 시 user me api 500 error 발생
`isExistDeviceToken` method 수정

Handle situations with more than one device-token

---

src/main/java/org/swmaestro/repl/gifthub/giftcard/controller/GiftcardController.java
src/main/java/org/swmaestro/repl/gifthub/giftcard/service/GiftcardService.java
src/main/java/org/swmaestro/repl/gifthub/vouchers/dto/VoucherShareResponseDto.java
src/main/java/org/swmaestro/repl/gifthub/vouchers/service/VoucherService.java

사용자가 기프티콘 공유 비밀번호를 알 방법이 없었음
기프티콘 공유 요청 시 비밀번호 응답

Add password field in voucher share request

---

src/main/java/org/swmaestro/repl/gifthub/vouchers/service/PendingVoucherService.java
src/main/java/org/swmaestro/repl/gifthub/vouchers/service/VoucherSaveService.java

사용자가 여러개의 voucher를 동시 등록할 상황을 고려하지 않아 `findByUserId`에서 여러개의 pending이 조회되는 에러 발생
pending delete 시, user가 아닌 pending id를 기준으로 삭제하도록 변경

Modify pending delete method by pending-id

---

src/main/java/org/swmaestro/repl/gifthub/giftcard/repository/GiftcardRepository.java
src/main/java/org/swmaestro/repl/gifthub/giftcard/service/GiftcardService.java
src/main/java/org/swmaestro/repl/gifthub/vouchers/controller/VoucherController.java
src/main/java/org/swmaestro/repl/gifthub/vouchers/service/VoucherSaveService.java
src/main/java/org/swmaestro/repl/gifthub/vouchers/service/VoucherService.java
src/test/java/org/swmaestro/repl/gifthub/vouchers/controller/VoucherControllerTest.java

- 기프티콘 공유 취소 API 구현 필요성 대두
- 기프티콘 공유 취소 API 구현
없음

Implement voucher-share cancel api

---

src/main/java/org/swmaestro/repl/gifthub/giftcard/controller/GiftcardController.java

- 공유하기 페이지를 랜더링하기 위한 API 요청 시 CORS 에러 발생 
- `@CrossOrigin` 어노테이션을 통해 특정 origin에 대해서만 해당 api 접근 허용
- 없음

Resolve CORS error

---

src/main/java/org/swmaestro/repl/gifthub/exception/TimeoutException.java
src/main/java/org/swmaestro/repl/gifthub/vouchers/service/GptService.java
src/main/java/org/swmaestro/repl/gifthub/vouchers/service/VoucherSaveService.java
src/main/resources/gpt/question.txt

- GPT Response Json 파싱 에러
- GPT에 많은 요청을 한번에 보냈을 때 응답이 안오다가 502에러 발생
- Prompt 수정
- `handleGptResponse`에서 15초 이상이 지나도 응답이 안오면 에러 발생

Update GPT prompt and Handle GPT response time out exception

---

src/main/java/org/swmaestro/repl/gifthub/giftcard/dto/GiftcardResponseDto.java
src/main/java/org/swmaestro/repl/gifthub/giftcard/service/GiftcardService.java
src/main/java/org/swmaestro/repl/gifthub/vouchers/service/BrandService.java
src/test/java/org/swmaestro/repl/gifthub/giftcard/contorller/GiftcardControllerTest.java

- FE에서 giftcard 정보 요청 시 브랜드 및 상품 정보도 받길 원함
- DTO 수정 및 로직 변경
- 없음

Add brand-info & product-info to giftcard-response-dto

---

src/main/java/org/swmaestro/repl/gifthub/giftcard/dto/GiftcardResponseDto.java
src/main/java/org/swmaestro/repl/gifthub/giftcard/service/GiftcardService.java
src/main/java/org/swmaestro/repl/gifthub/vouchers/controller/BrandController.java
src/main/java/org/swmaestro/repl/gifthub/vouchers/dto/BrandReadResponseDto.java
src/main/java/org/swmaestro/repl/gifthub/vouchers/service/BrandService.java
src/test/java/org/swmaestro/repl/gifthub/giftcard/contorller/GiftcardControllerTest.java
src/test/java/org/swmaestro/repl/gifthub/vouchers/controller/BrandControllerTest.java

`Giftcard` GET 요청 시, `brand`와 `product` 필드에서 CamelCase로 응답이 반환됨
`entity`가 아닌 `DTO`로 응답하도록 함

Chagne Giftcard Response from CamelCase

---

src/main/java/org/swmaestro/repl/gifthub/vouchers/dto/VoucherReadResponseDto.java
src/main/java/org/swmaestro/repl/gifthub/vouchers/service/VoucherService.java

- FE에서 기프티콘 조회 시 `is_shared` attribute 추가 요청
- dto 수정
- voucher-service 로직 수정
- 없음

Add 'is-shared' field

---

src/main/java/org/swmaestro/repl/gifthub/giftcard/controller/GiftcardController.java

- [x] 버그 수정
- giftcard 조회 시 cors 에러 발생
- @CrossOrigin 의 origins 옵션의 `,` 뒤  공백 제거

Write PULL_REQUEST_TEMPLATE.md (#3)

---

src/main/java/org/swmaestro/repl/gifthub/vouchers/controller/VoucherController.java
src/main/java/org/swmaestro/repl/gifthub/vouchers/dto/VoucherAutoSaveRequestDto.java
src/main/java/org/swmaestro/repl/gifthub/vouchers/service/GptService.java
src/main/java/org/swmaestro/repl/gifthub/vouchers/service/StorageService.java
src/main/java/org/swmaestro/repl/gifthub/vouchers/service/VoucherSaveService.java
src/main/java/org/swmaestro/repl/gifthub/vouchers/service/VoucherService.java
src/test/java/org/swmaestro/repl/gifthub/vouchers/controller/VoucherControllerTest.java

사용자에게 원본 이미지를 제공해야 함
원본 이미지를 조회하기 위한 presigned url 발급 요청 API 구현

Implement GET PresignedURL for get voucher image

---

src/main/java/org/swmaestro/repl/gifthub/exception/GptResponseException.java
src/main/java/org/swmaestro/repl/gifthub/exception/TimeoutException.java
src/main/java/org/swmaestro/repl/gifthub/vouchers/controller/VoucherController.java
src/main/java/org/swmaestro/repl/gifthub/vouchers/service/VoucherSaveService.java
src/test/java/org/swmaestro/repl/gifthub/vouchers/controller/VoucherControllerTest.java

pending voucher 생성이 비동기 작업안에서 실행되서 200 ok 응답을 받은 후에도 pending voucher 갯수가 0인 경우가 발생
기프티콘 자동 저장 메서드에서 pending voucher 생성 로직 분리

Solve situations when pending voucher is not created

---

src/main/java/org/swmaestro/repl/gifthub/vouchers/service/VoucherService.java

- 기프티콘 조회 시 shared가 정상 출력되지 않음
- enabled 메서드 사용
- X

Fix voucher's is-shared

---

src/main/java/org/swmaestro/repl/gifthub/giftcard/service/GiftcardService.java
src/main/java/org/swmaestro/repl/gifthub/vouchers/service/StorageService.java
src/main/java/org/swmaestro/repl/gifthub/vouchers/service/VoucherService.java

s3 get의 presigned url이 https로 나옴
문자열 대체로 http로 변경

Replace PreSigned URL in HTTPS

---

src/main/java/org/swmaestro/repl/gifthub/giftcard/repository/GiftcardRepository.java
src/main/java/org/swmaestro/repl/gifthub/giftcard/service/GiftcardService.java

'isExist' 에서 `IncorrectResultSizeDataAccessException`발생 
Optional -> List 로 변경

Handle error IncorrectResultSizeDataAccessException

---

src/main/java/org/swmaestro/repl/gifthub/auth/controller/UserController.java
src/main/java/org/swmaestro/repl/gifthub/vouchers/repository/VoucherRepository.java
src/main/java/org/swmaestro/repl/gifthub/vouchers/service/VoucherService.java

회원 탈퇴 시 기프티콘 삭제 처리(타 사용자가 등록 가능할 수 있도록) 필요 가능성 대두
회원 탈퇴 시 기프티콘 삭제 처리
없음

fix: add voucher-delete logic

---

src/main/java/org/swmaestro/repl/gifthub/auth/service/AppleService.java
src/main/java/org/swmaestro/repl/gifthub/auth/service/GoogleService.java
src/main/java/org/swmaestro/repl/gifthub/auth/service/KakaoService.java
src/main/java/org/swmaestro/repl/gifthub/auth/service/NaverService.java

OAuth 로그인 시 Internal server error message 가 나오고 있음
Exception handling 코드 추가

Handling NullPointerException

---

.github/workflows/dev-cd.yml
.github/workflows/dev-ci.yml
.github/workflows/prod-cd.yml
.github/workflows/prod-ci.yml
.gitignore
build.gradle
src/main/java/org/swmaestro/repl/gifthub/config/FCMConfig.java
src/main/java/org/swmaestro/repl/gifthub/vouchers/service/StorageService.java

1. key file이 development 환경 파일만 있어서 Production 환경에서 FCM 메세지 전송에 에러 발생
2. default 이미지 경로가 s3에서 `voucher`안에 있어서 접근이 불가했음 
1. application-dev.yml, application-prod.yml을 이용해 환경에 따라 key file 경로를 나눴음
2. default image url 변경

Divide Firebase Key file depending development and production

---

.github/workflows/prod-ci.yml

Production CI Test 실패 
CI시에는 `application-test.yml`이 실행되므로, json 디렉토리를 development 환경으로 변경

Handle Production CI test fail

---

src/main/java/org/swmaestro/repl/gifthub/auth/controller/UserController.java
src/main/java/org/swmaestro/repl/gifthub/vouchers/entity/Voucher.java
src/main/java/org/swmaestro/repl/gifthub/vouchers/repository/VoucherRepository.java
src/main/java/org/swmaestro/repl/gifthub/vouchers/service/VoucherService.java

- 바코드가 16자리인 기프티콘에 대한 대비책 필요 가능성 대두
- 바코드 컬럼 길이 수정
- X

Modify barcord column-length

---

src/main/java/org/swmaestro/repl/gifthub/vouchers/service/VoucherSaveService.java

기타 브랜드의 image_url이 null로 저장됨
try 문 밖으로 빼서 무조건 실행되도록 함

Set image-url Certainly in etc brand

---

src/main/java/org/swmaestro/repl/gifthub/vouchers/controller/VoucherController.java
src/main/java/org/swmaestro/repl/gifthub/vouchers/dto/VoucherUpdateResponseDto.java
src/main/java/org/swmaestro/repl/gifthub/vouchers/service/VoucherService.java
src/test/java/org/swmaestro/repl/gifthub/vouchers/controller/VoucherControllerTest.java

클라이언트의 voucher update return 값 변경 요청
`VoucherSaveResponseDto`를 변경하면 코드 커버리지가 넓어져서 `VoucherUpdateResponseDto`를 따로 생성함

Implement voucher-update-response-dto

---

src/main/java/org/swmaestro/repl/gifthub/vouchers/dto/VoucherUpdateResponseDto.java
src/main/java/org/swmaestro/repl/gifthub/vouchers/service/VoucherService.java

`VoucherUpdateResponseDto`에 `is_checked` 부재로 인한 에러 발생
`is_checked` 필드 추가

Add is-checked field

---

src/main/java/org/swmaestro/repl/gifthub/auth/repository/UserRepository.java
src/main/java/org/swmaestro/repl/gifthub/auth/service/UserService.java
src/main/java/org/swmaestro/repl/gifthub/vouchers/service/VoucherService.java

기프티콘 수동 등록 시 바코드 입력 안해도 저장됨
바코드 입력 안할 시 exception 발생하도록 함

Handle barcode null error exception

---

src/main/java/org/swmaestro/repl/gifthub/auth/repository/UserRepository.java

return type이 안맞음
`List`로 return type 변경함

Modify return type

---

src/main/java/org/swmaestro/repl/gifthub/vouchers/service/VoucherSaveService.java

다음과 같이 Exception에 따라 알림 메세지가 저장이 안되고 있음
`GptResponseException`, `GptTimeException` -> 등록에 실패했습니다. 다시 시도해 주세요.
`BusniessException` -> 이미 등록된 기프티콘 입니다.
`GptResponseException`, `GptTimeException`이 `BusniessException`을 상속받고 있어서 현재와 같은 상황이었음
조건을 다르게 하여 해결함

Modify notification message according to exception

---

src/main/java/org/swmaestro/repl/gifthub/notifications/config/VoucherBatchThreadConfig.java
src/main/java/org/swmaestro/repl/gifthub/notifications/config/VoucherExpirationBatchConfig.java
src/main/java/org/swmaestro/repl/gifthub/notifications/service/FCMNotificationItemWriter.java
src/main/java/org/swmaestro/repl/gifthub/notifications/service/FCMNotificationService.java
src/main/java/org/swmaestro/repl/gifthub/notifications/service/VoucherExpirationJobListener.java
src/main/java/org/swmaestro/repl/gifthub/vouchers/service/VoucherService.java
src/test/java/org/swmaestro/repl/gifthub/notifications/service/FCMNotificationItemWriterTest.java
src/test/java/org/swmaestro/repl/gifthub/notifications/service/VoucherBatchPerformanceTest.java

> 작성 배경
서비스에서 관리하는 모바일 상품권의 개수가 늘어날 경우 만료 알림 배치 작업의 처리 속도 개선이 필요할 것으로 판단하였습니다. 단일 스레드 방식으로는 대량의 상품권 유효 기간 알림 처리 시 실행 시간이 길어져 사용자에게 적시에 알림을 제공하기 어려울 수 있습니다. 특히 상품권 수가 증가함에 따라 성능 저하 문제가 더욱 심화될 것으로 예상됩니다.
>  해결 방법
Spring의 ThreadPoolTaskExecutor를 활용하여 병렬 처리 방식으로 전환했습니다.
1. ThreadPoolTaskExecutor 설정을 추가하여 CPU 코어 수에 기반한 최적의 스레드 풀 구성
2. FCM 알림 서비스를 스레드 안전하게 리팩토링(ConcurrentHashMap 활용)
3. 네트워크 오류에 대비한 지수 백오프 방식의 재시도 메커니즘 구현
4. 성능 측정을 위한 JobExecutionListener 추가 및 성능 비교 테스트 코드 작성
5. 스레드 풀 설정을 application.yml로 분리하여 환경별 유연한 구성 가능
이론적으로 병렬 처리는 동시 실행 스레드 수에 비례하여 성능 향상이 가능합니다(암달의 법칙). 실제 프로덕션 환경에서는 FCM API 호출, 네트워크 지연, DB 접근 등 I/O 바운드 작업이 많아 보다 효과적인 성능 개선을 기대하고 있습니다.
> 리뷰어에게 말하고 싶은 것, 유의 깊게 봐주었으면 하는 것, 의문점 등
```mermaid
flowchart TD
A[Spring Batch Job:<br>voucherExpirationNotificationJob] --> …
```

✨ Implement Multi-threading for Voucher Expiration Notification Batch Processing
