SWM-REPL/gifthub-was

src/main/java/org/swmaestro/repl/gifthub/vouchers/controller/BrandController.java, src/main/java/org/swmaestro/repl/gifthub/vouchers/controller/VoucherController.java, src/main/java/org/swmaestro/repl/gifthub/vouchers/entity/Product.java, src/test/java/org/swmaestro/repl/gifthub/vouchers/controller/BrandControllerTest.java
동일한 상품명이더라도 브랜드가 다르다면 저장이 되도록 해야함
기존 Product Entity의 name 컬럼에 unique 옵션 삭제
- ex) `CU의 바나나우유`와 `GS25의 바나나우유`는 다른 기프티콘이지만 동일한 이름의 상품임
- 추가적으로 이태우 멘토님께서 말씀하신대로 API Path가 단수인 것들을 복수로 변경하였습니다.
=> Remove unique option to product name

src/main/java/org/swmaestro/repl/gifthub/vouchers/controller/VoucherController.java, src/main/java/org/swmaestro/repl/gifthub/vouchers/dto/VoucherReadResponseDto.java, src/main/java/org/swmaestro/repl/gifthub/vouchers/dto/VoucherUseRequestDto.java, src/main/java/org/swmaestro/repl/gifthub/vouchers/dto/VoucherUseResponseDto.java, src/main/java/org/swmaestro/repl/gifthub/vouchers/service/VoucherService.java, src/test/java/org/swmaestro/repl/gifthub/vouchers/controller/VoucherControllerTest.java
클라이언트에서 요청하여 기프티콘 사용 시, voucher 테이블의 `balance`가 수정되고자 하였습니다.
`product price`(정가)를 `VoucherReadResponseDto`로 전달하여 클라이언트에서 확인이 가능하고자 하였습니다.
`RequestBody`로 `amount`나 `place`를 안보낸 경우 예외처리 로직을 추가했습니다.
기프티콘 사용시 voucher 테이블의 `balance`가 차감도록 로직을 수정하였습니다. 
`voucherReadDto`에 `product`의 `price` 필드를 추가하였습니다.
❗️`VoucherUseRequestDto`의 `amount`가 `int`형인 경우 null 처리가 안되고 자동으로 0으로 초기화 되기 때문에 예외처리를 위해 `Integer`형으로 선언하였습니다.
=> Save change of balance to voucher table and Return product price when voucher is used

src/main/java/org/swmaestro/repl/gifthub/auth/controller/UserController.java, src/main/java/org/swmaestro/repl/gifthub/auth/dto/MemberReadResponseDto.java, src/main/java/org/swmaestro/repl/gifthub/auth/service/MemberServiceImpl.java, src/main/java/org/swmaestro/repl/gifthub/vouchers/controller/VoucherController.java, src/main/java/org/swmaestro/repl/gifthub/vouchers/repository/VoucherRepository.java, src/main/java/org/swmaestro/repl/gifthub/vouchers/service/VoucherService.java, src/test/java/org/swmaestro/repl/gifthub/vouchers/controller/VoucherControllerTest.java
프론트엔드에서 상품권 목록 조회 시 쿼리 스트링을 통해 사용자 아이디를 입력받자는 의견을 제시하였음
Voucher List 조회 API에 `?member_id=[member_id]`를 입력하면 해당 사용자의 기프티콘 목록을 조회하도록 수정하였음
- Voucher LIst 조회 시 반드시 member_id 옵션이 필요하도록 구현하였습니다.
- 기존 `MemberReadResponseDto`에 `username`이 존재하지 않아 추가하였습니다.
=> Add query-string 'member_id' to read voucher-list API

src/main/java/org/swmaestro/repl/gifthub/auth/repository/DeviceTokenRepository.java, src/main/java/org/swmaestro/repl/gifthub/auth/service/DeviceTokenService.java
FCM을 통해 알림 서비스를 구현하기 위해, 사용자의 DeviceToken 관리 필요성 대두
- DeviceToken 관리 로직 구현
- 저장
- 존재 여부 판별
- 조회
- 하나의 회원에 해당하는 전체 토큰 조회
- 하나의 디바이스 토큰 조회
- 삭제
추후 클라이언트에서 DeviceToken을 주는 로직이 구현될 경우 별도 PR을 통해 DeviceToken 저장 로직을 활용하는 기능을 구현할 예정입니다.
=> Implement divice-token management logic

src/main/java/org/swmaestro/repl/gifthub/notifications/NotificationType.java, src/main/java/org/swmaestro/repl/gifthub/notifications/dto/NotificationReadResponseDto.java, src/main/java/org/swmaestro/repl/gifthub/notifications/service/NotificationService.java, src/test/java/org/swmaestro/repl/gifthub/notifications/controller/NotificationControllerTest.java
와이프레임에 맞게 클라이언트에서 notificatio-read-response-dto의 type을 `String` 형식으로의 변경 요청이 있었습니다.
**기존**
```json
{
"status_code": 200,
"message": "알림 목록 조회에 성공하였습니다!",
"data": [
{
"id": 3,
"type": "EXPIRATION",
"message": "스타벅스에서 사용할 수 있는 기프티콘 기한이 5일 남았습니다.",
"notified_at": "2023-08-01T13:06:39.440224",
"voucher_id": 2
}
]
}
```
**수정**
```json
{
"status_code": 200,
"message": "알림 목록 조회에 성공하였습니다!",
"data": [
{
"id": 3,
"type": "유효기간 임박 알림",
"message": "스타벅스에서 사용할 수 있는 기프티콘 기한이 5일 남았습니다.",
"notified_at": "2023-08-01T13:06:39.440224",
"voucher_id": 2
}
]
}
```
`NotificationService`의 mapToDto 에서 문자열로 매핑해주는 로직을 추가했습니다.
❗️현재는 알림 종류가 2가지(위치기반 사용추천 알림은 하지 않으니까 사실상 유효기간 알림 한가지라고 생각합니다.)여서 삼항 연산자로 쉽게 구현할 수 있었지만, 알림 종류가 늘어난다면 고민해봐야할 것 같습니다.
=> Change type from  NotificationType to String in Notification-Read-Response-Dto

src/main/java/org/swmaestro/repl/gifthub/notifications/controller/NotificationController.java, src/main/java/org/swmaestro/repl/gifthub/notifications/dto/NotificationReadResponseDto.java, src/main/java/org/swmaestro/repl/gifthub/notifications/entity/Notification.java, src/main/java/org/swmaestro/repl/gifthub/notifications/service/NotificationService.java, src/test/java/org/swmaestro/repl/gifthub/notifications/controller/NotificationControllerTest.java
[클라이언트에서 알림 확인 여부를 서버 측에서 관리하는 것을 요청하였습니다.](https://swm-repl.atlassian.net/browse/GH-251)
알림 상세 조회하는 API를 구현하였고, 상세 조회 시 `notification`의 `check_at`  시간을 기록하여 저장하였습니다.
`notification` 엔티티의 `checked_at` 을 `setter`를 이용해 값을 변경해주었습니다.
=> Implement notification read API and Save checked-at

src/main/java/org/swmaestro/repl/gifthub/auth/entity/DeviceToken.java, src/main/java/org/swmaestro/repl/gifthub/notifications/service/FCMNotificationService.java, src/main/java/org/swmaestro/repl/gifthub/notifications/service/ScheduledTasks.java
유효 기간 만료가 임박한 기프티콘이 존재함에도 불구하고 사용자에게 푸시 알림이 전송되지 않음
- Date 조회 로직 변경
- Voucher 조회 로직 변경
- `new Date().getYear`의 경우 `2023`이 아닌 `0123`을 가져오는 것을 확인하였고, 이에 따라 계산 로직을 수정하였음(시작연도가 1900으로 시작하는 것으로 추정)
- 기프티콘 리스트를 가져울 때 stream을 통해 유효 기간 만료 임박한 기프티콘만 가져오도록 함으로써 푸시 알림을 전송할 때 걸리는 시간을 단축하였음
- 기존 : 모든 기프티콘의 유효기간을 일일히 조회 후 처리
- 현재 : stream을 통해 유효 기간 만료 임박 기프티콘에 한해 처리
- Todo : 로그아웃 시 디바이스 토큰 삭제 필요
=> Fixed Push Notification

src/main/java/org/swmaestro/repl/gifthub/auth/controller/AuthController.java, src/main/java/org/swmaestro/repl/gifthub/auth/dto/SignOutDto.java, src/main/java/org/swmaestro/repl/gifthub/auth/service/AuthService.java, src/main/java/org/swmaestro/repl/gifthub/auth/service/AuthServiceImpl.java, src/test/java/org/swmaestro/repl/gifthub/auth/controller/AuthControllerTest.java
사용자가 디바이스에서 로그아웃하더라도 푸시 알림이 전송되는 현상이 발생하였음
사용자가 로그아웃 시 device token을 전송하면 서버에서 해당 로직을 수행하여 DB에 device token 삭제 처리
- 컨트롤러의 ResponseEntity 반환 방법을 한 번 수정해봤습니다! 어떤가요? ㅎㅎ
=> Add device-token deletion logic when sign-out

src/main/java/org/swmaestro/repl/gifthub/notifications/service/NotificationService.java, src/main/java/org/swmaestro/repl/gifthub/notifications/service/ScheduledTasks.java
사용자가 알림을 조회하였을 때 알림 전송일자가 보이지 않는 문제 발생
강제로 알림 전송 시 `created_at` 컬럼에 현재 날짜 및 시간을 저장하도록 함
- 없음
=> Fixed issue where created_at was not being saved

build.gradle, src/main/java/org/swmaestro/repl/gifthub/vouchers/controller/VoucherController.java, src/main/java/org/swmaestro/repl/gifthub/vouchers/dto/PresignedUrlResponseDto.java, src/main/java/org/swmaestro/repl/gifthub/vouchers/service/StorageService.java
이미지 등록 시 서버 부하를 줄이기 위해
AWS S3 Presigned URL을 발급받아 Client가 이미지를 직접 저장할 수 있는 URL을 제공하도록 구현하였음
- **Presigned-url을 통한 이미지 등록 시 HTTP 메서드는 `PUT`임**
- Request
- Response
- 우려점
- 현재 파일의 확장자(혹은) 타입이나 크기에 대해 소스코드에서 제어를 하고 있지는 않음
- bucket에서 제어를 해야함 => 완료
- 관련 정리 : https://jinlee.kr/web/2023-09-18-s3-presiend-url/
=> Generate S3 Presigned-url

.github/workflows/on_pull_request.yml, .github/workflows/on_push.yml, build.gradle, src/main/java/org/swmaestro/repl/gifthub/filter/LoggingFilter.java, src/main/resources/console-appender.xml, src/main/resources/file-error-appender.xml, src/main/resources/file-info-appender.xml, src/main/resources/file-warn-appender.xml, src/main/resources/logback-spring.xml
WAS 서버의 로그를 저장하기 위한 Logging 구현 및 Logging Filter 구현
- log 관련 .xml 파일 정의
- LoggingFilter 구현
- 우리 서비스에 맞게 잘 작성해보고 싶었으나 아직 많이 부족할 것 같습니다...
- 추후 수정 및 보완이 필요하지 않을까 싶습니다.
- 현재는 API 요청 시 request-body 출력, response-body 출력 등 API 단위에 대해서 로깅이 이루어지고 있습니다.
=> Implement Logging Filter

src/main/java/org/swmaestro/repl/gifthub/auth/controller/AuthController.java, src/main/java/org/swmaestro/repl/gifthub/auth/service/GoogleService.java, src/test/java/org/swmaestro/repl/gifthub/auth/controller/AuthControllerTest.java
MVP 2.0을 위한 Google OAuth 문제 해결
OAuth 요청 로직 FE와 분배 및 코드 수정
.
=> Modify Google OAuth logic

.github/workflows/on_push.yml
WAS 서버에 정상적으로 배포가 되지 않는 현상 발생
`docker system prune -a -f` 명령어를 추가하여 서버에 존재하는 도커 이미지들을 삭제하도록 함
도와주셔서 감사합니다 :)
=> Add docker prune cmd

src/main/java/org/swmaestro/repl/gifthub/config/SecurityConfig.java, src/test/java/org/swmaestro/repl/gifthub/auth/controller/AuthControllerTest.java
- FE의 401 및 403 에러 발생 시 예외 처리 형식 단일화 요청
- SecurityConfig 수정
- 현재 에러 코드는 400, response body의 `status_code`를 401 혹은 403으로 처리 중
- 추후 API 응답 형식 수정 시 재수정 예정
=> Modify security exception-handling

src/main/java/org/swmaestro/repl/gifthub/notifications/NotificationType.java, src/main/java/org/swmaestro/repl/gifthub/notifications/controller/NotificationController.java, src/main/java/org/swmaestro/repl/gifthub/notifications/entity/Notification.java, src/main/java/org/swmaestro/repl/gifthub/notifications/service/FCMNotificationService.java, src/main/java/org/swmaestro/repl/gifthub/notifications/service/NotificationService.java
- FE에서 Notification 등록 시 `created_at`이 저장되지 않고 있다는 이슈 건의
- 이전에 `created_at`을 직접 삽입함으로써 해결하였던 이슈였음 => 이전에 보냈던 알림은 `created_at`이 수정되지 않기 때문에 건의된 이슈로 판단됨
- `AuditingEntityListener`를 통해 구현되도록 리팩토링하였음
- 이전에 해결하였던 이슈였으나 올바르게 해결이 안된 줄 알고 있었습니다.
- 하지만 보냈던 알림은 created_at이 수정되지 않기 때문에 FE에서 건의한 것으로 판단됩니다.
=> Fixed an issue where `create_date` was not saved when registering a notification

src/main/java/org/swmaestro/repl/gifthub/config/SecurityConfig.java, src/main/java/org/swmaestro/repl/gifthub/notifications/controller/NotificationController.java
만료된 토큰으로 알림 목록 조회 시 500 에러 발생
- 기존 공지 알림 전송 시 `POST` 방식으로 `/notification`에 전송하였기 때문에 SecurityConfig에 해당 uri를 열어두었음 => 삭제 처리
- 추후 공지 알림 전송을 관리자만 허용하도록 수정이 필요할 것으로 판단됩니다.
=> Modify error-code from 500 to 400(401)

src/main/java/org/swmaestro/repl/gifthub/util/QueryTemplateReader.java, src/main/java/org/swmaestro/repl/gifthub/vouchers/entity/Product.java, src/main/java/org/swmaestro/repl/gifthub/vouchers/entity/Voucher.java, src/main/java/org/swmaestro/repl/gifthub/vouchers/service/BrandService.java, src/main/java/org/swmaestro/repl/gifthub/vouchers/service/GptService.java, src/main/java/org/swmaestro/repl/gifthub/vouchers/service/ProductService.java, src/main/java/org/swmaestro/repl/gifthub/vouchers/service/SearchService.java, src/main/java/org/swmaestro/repl/gifthub/vouchers/service/StorageService.java, src/main/java/org/swmaestro/repl/gifthub/vouchers/service/VoucherSaveService.java, src/main/java/org/swmaestro/repl/gifthub/vouchers/service/VoucherService.java, src/main/resources/gpt/question.txt, src/main/resources/gpt/voucher-query-template.json
DB에 브랜드, 상품 정보가 없는 기프티콘도 저장할 수 있도록 변경하고자 했습니다.
검색결과가 없을 경우에
- `brand` -> 기타'
- `product name` -> 사용자가 저장하려는 기프티콘 상품명
- `brand` 이미지, `product` 이미지 -> `logo.png`
- `price` -> null
- `is_reusable` -> 0 (금액권 X)
으로 저장되게 했습니다.
기타 product, 즉 product price가 null 인 경우의 voucher는 자유롭게 balance 수정이 가능하게하고
product price가 null 이 아닌 경우에는 voucher balance의 값은 product price를 넘지 못하도록 하였습니다.
=> Implement Voucher-Save-Method with No DB Information

src/main/java/org/swmaestro/repl/gifthub/util/ProductNameProcessor.java, src/main/java/org/swmaestro/repl/gifthub/vouchers/service/VoucherSaveService.java, src/main/resources/gpt/question.txt, src/main/resources/opensearch/voucher-query-template.json
- Opensearch의 tokenizer를 `ngram`으로 바꾸고 나서, 검색 score에 이상이 있었습니다.
그 이유는 상품명이 `50,000원` 인 경우 `0`의 개수가 많아서 `500,000원`이 검색되는 것이었습니다.
-  product_name의 금액 숫자 표기를 단위 숫자 표기로 변환하는 전처리 과정을 추가했습니다.
- 500원 -> 5백원
- 50,000원 -> 5만원
- 검색 시, 브랜드로 먼저 필터링 한 후, 유사한 product_name을 검색하도록 쿼리를 변경하였습니다.
- `brand_name`: 스타벅스, `product_name` :  문화 상품권 -> 검색 X 
`ProductNameProcessor.java`를 우선 `util` 디렉토리에 넣긴 했지만,  `voucher` 디렉토리에 위치시킬지 `util` 디렉토리에 위치시키는게 좋을지 고민입니다.
=> Preprocess to korean unit in product-name to search performance improvements 

src/main/java/org/swmaestro/repl/gifthub/notifications/NotificationType.java, src/main/java/org/swmaestro/repl/gifthub/notifications/entity/Notification.java, src/main/java/org/swmaestro/repl/gifthub/notifications/service/FCMNotificationService.java, src/main/java/org/swmaestro/repl/gifthub/vouchers/controller/VoucherController.java, src/main/java/org/swmaestro/repl/gifthub/vouchers/dto/ProductReadResponseDto.java, src/main/java/org/swmaestro/repl/gifthub/vouchers/dto/VoucherListResponseDto.java, src/main/java/org/swmaestro/repl/gifthub/vouchers/entity/PendingVoucher.java, src/main/java/org/swmaestro/repl/gifthub/vouchers/entity/Product.java, src/main/java/org/swmaestro/repl/gifthub/vouchers/repository/PendingVoucherRepository.java, src/main/java/org/swmaestro/repl/gifthub/vouchers/service/PendingVoucherService.java, src/main/java/org/swmaestro/repl/gifthub/vouchers/service/VoucherSaveService.java, src/main/java/org/swmaestro/repl/gifthub/vouchers/service/VoucherService.java, src/test/java/org/swmaestro/repl/gifthub/vouchers/controller/VoucherControllerTest.java
비동기로 처리되는 기프티콘 자동 등록 기능에서 처리 중인 기프티콘의 상태를 알려주고자 하였습니다.
1. 기프티콘 자동 등록 요청 -> 해당 member의 pending_voucher row 추가
2. 등록 완료 -> 해당 member의 pending_voucher row 삭제
3. 기프티콘 목록 조회 api 요청 -> 해당 member의 pending_voucher count 응답
기프티콘 수동 등록 / 자동 등록을 API를 분리하고
기존의 POST `/vouchers`를 기프티콘 수동 등록이라는 의미로 `/vouchers/manual` 로 바꾸고
현재의 POST `/vouchers/test`를 `/vouchers`로 바꾸는 건 어떨까요? 의견 주시면 감사하겠습니다!
=> Implement Voucher Pending when voucher is registered automatically

src/main/java/org/swmaestro/repl/gifthub/auth/controller/UserController.java, src/main/java/org/swmaestro/repl/gifthub/auth/entity/OAuth.java, src/main/java/org/swmaestro/repl/gifthub/auth/repository/OAuthRepository.java, src/main/java/org/swmaestro/repl/gifthub/auth/service/AppleService.java, src/main/java/org/swmaestro/repl/gifthub/auth/service/GoogleService.java, src/main/java/org/swmaestro/repl/gifthub/auth/service/KakaoService.java, src/main/java/org/swmaestro/repl/gifthub/auth/service/MemberService.java, src/main/java/org/swmaestro/repl/gifthub/auth/service/NaverService.java, src/main/java/org/swmaestro/repl/gifthub/auth/service/OAuth2Service.java, src/main/java/org/swmaestro/repl/gifthub/auth/service/OAuthService.java, src/test/java/org/swmaestro/repl/gifthub/auth/controller/UserControllerTest.java
사용자가 하나의 계정에 연결된 여러 개의 OAuth 계정을 해지하도록 함
사용자 계정에 연결된 OAuth 계정 해지 API 구현
- 현재 OAuth 계정 정보 삭제 시 soft-delete가 아닌 hard-delete 중 인데 이 점이 서비스 구현에 문제가 될 지와 수정이 필요할 지 의견이 궁금합니다!
=> implement delete OAuth-info API

src/main/java/org/swmaestro/repl/gifthub/vouchers/dto/VoucherUseResponseDto.java, src/main/java/org/swmaestro/repl/gifthub/vouchers/entity/VoucherUsageHistory.java, src/main/java/org/swmaestro/repl/gifthub/vouchers/service/VoucherService.java, src/main/java/org/swmaestro/repl/gifthub/vouchers/service/VoucherUsageHistoryService.java
Product price가 null 인 상품이 생기며 기프티콘 사용 로직에 문제가 생겼었습니다.
DB에 없는 정보를 가진 Product가 생성될 때 **reusable**을 1로 설정합니다.
**non-reusable voucher** 혹은 **voucher balance가 null** 인 voucher를 사용하려고 할 때 클라이언트에서 사용 요청 금액을 **null** 로 보냅니다.
다음과 같이 예외처리를 하였습니다.
Voucher | DB에 정보 X | DB에 정보 X | DB에 정보 O | DB에 정보 O
-- | -- | -- | -- | --
product price | null | null | not null | not null
voucher balance | null | not null | not null | not null
reusable | 1 | 1 | 0 | 1
requestDto.amount == null | 사용 완료 | 400 에러 | 사용 완료 | 400에러
requestDto.amount == not null | 400 에러 | 사용 가능 | 400에러 | 사용 가능
=> Use Voucher that Product Price is null

src/main/java/org/swmaestro/repl/gifthub/vouchers/controller/VoucherController.java, src/main/java/org/swmaestro/repl/gifthub/vouchers/dto/GptResponseDto.java, src/main/java/org/swmaestro/repl/gifthub/vouchers/dto/SearchResponseDto.java, src/main/java/org/swmaestro/repl/gifthub/vouchers/service/VoucherService.java, src/test/java/org/swmaestro/repl/gifthub/vouchers/controller/VoucherControllerTest.java
디비에 없는 기프티콘이 특정 상품으로 분류된 경우 사용자가 기프티콘 수정을 통해서도 올바르게 분류할 수 있도록 했습니다.
1. 브랜드는 다른데 상품명이 같은 경우가 있을 수 있음 
-> 상품명 검색 시 `productService.read(voucher.getBrand().getId(), voucher.getProduct().getName());`로 변경
3. 사용자가 이미 브랜드 수정을 한번 했음(기타 -> 특정 브랜드로) 
- voucher.getBrand와 voucher.getProduct.getBrand가 다름
- Product 검색 결과가 안나옴 -> voucher.getBrand로 먼저 검색 후 없으면 기타 브랜드로 등록된 것 검색
**[사용자 시나리오]** 
기프티콘이 잘못 저장된 것을 사용자가 발견 -> 수정하려고 함
- 브랜드 만 수정하려고 함
- 기존에 있는 브랜드 -> 기존 브랜드로 저장
- 기존에 없는 브랜드 -> 기타 브랜드 저장
- 상품명 만 수정하려고 함
- 브랜드 -> 기존 voucher 브랜드
- 브랜드와 상품명 이름 같이 검색
- 기존에 있는 Product -> 해당 Product로 저장
- 기존에 없는 Product -> 기타 브랜드로 새로운 Product 생성 후 저장
- 브랜드 상품명 동시에 수정하려고함
- 브랜드 수정 먼저
- 기존에 있는 브랜드 -> 그걸로
- 기존에 없는 브랜드 -> ‘기타’
- 상품명 수정
-	브랜드와 상품명 이름 같이 검색	 
- 기존에 있는 Product -> 그걸로
- 기존에 없는 Product -> 기타 브랜드로 새로운 Product …
=> Modify Voucher Update-logic to-update voucher with no-db-information

src/main/java/org/swmaestro/repl/gifthub/auth/service/AuthService.java
1. Sign-in 시 refresh token 저장이 안되고 있었음
2. Device token 삭제하는 API 를 따로 분리했는데, sign-out 안에 delete device token 로직이 중복되고 있었음
=> Modify refresh-token save and duplicated device-token logic

src/main/java/org/swmaestro/repl/gifthub/auth/entity/OAuth.java, src/main/java/org/swmaestro/repl/gifthub/auth/entity/User.java, src/main/java/org/swmaestro/repl/gifthub/auth/repository/OAuthRepository.java, src/main/java/org/swmaestro/repl/gifthub/auth/service/AppleService.java, src/main/java/org/swmaestro/repl/gifthub/auth/service/GoogleService.java, src/main/java/org/swmaestro/repl/gifthub/auth/service/KakaoService.java, src/main/java/org/swmaestro/repl/gifthub/auth/service/NaverService.java, src/main/java/org/swmaestro/repl/gifthub/auth/service/OAuthService.java, src/main/java/org/swmaestro/repl/gifthub/auth/service/UserService.java
1. google user-info response 제거
2. OAuth로 로그인 -> 회원탈퇴-> 재로그인 시 기존 유저로 로그인 되는 문제
3. 회원 탈퇴 시, OAuth 삭제 안됨 
1. 회원 탈퇴 시, OAuth 테이블에 있는 모든 정보 deleted_at 추가 - aeee02f61e67e02b11dabed5394449709481e98b , 64a1a6e73b7219e27c5115f6122de64bc0b4ca1f
2. JPA method 변경으로 deleted_at이 null인 것만 is_exist로 판정 - 94d7f0d449a525bf04bcff19cfdbf4b06d3573c6 , ea7ac68995c726f56f3b7d3aeb0762a5dd15013b, 930be7f1e8d361e6d5b9e8c522c7a644332c6008
=> Modify OAuth Logic when User Deleted and Re sign-in

src/main/java/org/swmaestro/repl/gifthub/config/SecurityConfig.java, src/main/java/org/swmaestro/repl/gifthub/giftcard/config/GiftcardConfig.java, src/main/java/org/swmaestro/repl/gifthub/giftcard/contorller/GiftcardController.java, src/main/java/org/swmaestro/repl/gifthub/giftcard/dto/GiftcardRequestDto.java, src/main/java/org/swmaestro/repl/gifthub/giftcard/dto/GiftcardResponseDto.java, src/main/java/org/swmaestro/repl/gifthub/giftcard/entity/Giftcard.java, src/main/java/org/swmaestro/repl/gifthub/giftcard/service/GiftcardService.java, src/main/java/org/swmaestro/repl/gifthub/util/BasicAuthenticationDecoder.java, src/main/java/org/swmaestro/repl/gifthub/util/ByteArrayUtils.java, src/test/java/org/swmaestro/repl/gifthub/giftcard/contorller/GiftcardControllerTest.java
- 기프티콘 공유하기 기능을 제공하기 위해 공유하기 정보를 조회하는 기능 필요
- 공유하기 정보 조회 API 구현
- BasicAuthenticationDecoder 구현
- Example Request, Response
=> Implement read giftcard-info API

src/main/java/org/swmaestro/repl/gifthub/auth/dto/UserInfoResponseDto.java, src/main/java/org/swmaestro/repl/gifthub/auth/repository/DeviceTokenRepository.java, src/main/java/org/swmaestro/repl/gifthub/auth/service/UserService.java
유효기간알림, 기프티콘 등록 성공/실패 여부 알림 등 정보성 알림에 대한 수신 동의 관리 필요성 대두
- 회원 가입 시 기본적으로 devicetoken을 저장
- 마이페이지에서 알림 수신 거부 시 -> devicetoken 삭제 API 호출
로 관리하기로 클라이언트와 협의함
- 내 정보 조회 API를 통해 해당 회원이 알림 동의 현황을 파악할 수 있도록 함
정보성 알림과 광고성 알림 법률의 차이가 있다는 것을 파악했고, [GH-301](https://swm-repl.atlassian.net/jira/software/projects/GH/boards/1?selectedIssue=GH-301)에 관련 자료 첨부하였습니다.
[GH-301]: https://swm-repl.atlassian.net/browse/GH-301?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add notification agreement field in user-info-dto

src/main/java/org/swmaestro/repl/gifthub/giftcard/contorller/GiftcardController.java, src/main/java/org/swmaestro/repl/gifthub/giftcard/entity/Giftcard.java, src/main/java/org/swmaestro/repl/gifthub/giftcard/service/GiftcardService.java, src/test/java/org/swmaestro/repl/gifthub/giftcard/contorller/GiftcardControllerTest.java
- `공유하기 기능을 통한 기프티콘 양도 기능` 도입 필요
- 기프티콘 소유자 변경 API 구현
- 순환참조로 인해 GiftCardService가 VoucherService가 아닌 VoucherRepository를 호출하고 있습니다.
=> Implement change-voucher owner to giftcard API

src/main/java/org/swmaestro/repl/gifthub/auth/service/OAuthService.java, src/main/java/org/swmaestro/repl/gifthub/auth/service/UserService.java, src/main/java/org/swmaestro/repl/gifthub/filter/JwtAuthenticationFilter.java, src/main/java/org/swmaestro/repl/gifthub/util/JwtProvider.java
탈퇴한 회원으로 내정보 조회 시, 500에러 발생
최상단 Filter인 `JwtAuthenticationFilter`에서 `UsernameNotFoundException` 핸들링 하도록 하여 401 에러를 응답으로 보내게 함
[관련 자료 참고](https://jhkimmm.tistory.com/29)
=> Modify UsernameNotFoundException Error handling

src/main/java/org/swmaestro/repl/gifthub/auth/entity/User.java, src/main/java/org/swmaestro/repl/gifthub/auth/repository/UserRepository.java, src/main/java/org/swmaestro/repl/gifthub/auth/service/AuthService.java, src/main/java/org/swmaestro/repl/gifthub/auth/service/UserService.java
일반 로그인 계정으로 가입 후, 탈퇴했던 계정의 username으로는 가입이 안됐었음
- username의 unique 속성해제
- 	`findByUsername`의 결과가 2개 이상으로 나와서 에러발생하여 `findByUsernameAndDeletedIsNull`메서드로 변경
=> Re Sign-up a user who previously left

src/main/java/org/swmaestro/repl/gifthub/auth/dto/UserUpdateRequestDto.java, src/main/java/org/swmaestro/repl/gifthub/auth/service/UserService.java, src/main/java/org/swmaestro/repl/gifthub/auth/type/Role.java
- 회원 정보 수정 시 닉네임 길이가 12자가 넘을 경우 500 에러 바생
- 닉네임 길이에 따른 예외처리 로직 추가
- 없음
=> Add nickname-length exception-handling logic

src/main/java/org/swmaestro/repl/gifthub/auth/dto/UserInfoResponseDto.java, src/main/java/org/swmaestro/repl/gifthub/auth/entity/User.java, src/main/java/org/swmaestro/repl/gifthub/auth/service/UserService.java
클라이언트로부터의 비회원 여부 정보 요청
user의 role 정보 응답
다음고 같이 구현했을 때, 응답이 이렇게 왔습니다.
1. 코드
2. 응답
Lombok Getter와 Jackson에서 `is` prefix를 붙이면 무슨 문제가 발생하는 것 같은데, 아직 이해는 잘 못했습니다.
일단 빠른 구현을 위해 강제로 이름을 바꿔주었습니다.
슬쩍 찾아봤는데 아마 `@Getter` 랑 `Jackson`의 직렬화 문제인 것 같습니다.
[참고 자료입니다.](https://stackoverflow.com/questions/40022600/duplicate-boolean-fields-in-json)
=> Implement is-anonymous field in user-info-dto

src/main/java/org/swmaestro/repl/gifthub/auth/entity/User.java, src/main/java/org/swmaestro/repl/gifthub/auth/service/UserService.java, src/main/java/org/swmaestro/repl/gifthub/notifications/controller/NotificationController.java, src/test/java/org/swmaestro/repl/gifthub/notifications/controller/NotificationControllerTest.java
기존 알림동의하기 관리 진행할 시, pending 처리 후 새로고침이 안됨
- user entity에서 만료 알림 수신 여부를 관리
- 별도의 API로 만료 알림 수신 여부를 변경할 수 있도록 함
요청, 응답 형식은 postman을 참고해주세요.
=> Implement expiration notifications Allow and Deny API

src/main/java/org/swmaestro/repl/gifthub/auth/service/AppleService.java, src/main/java/org/swmaestro/repl/gifthub/auth/service/GoogleService.java, src/main/java/org/swmaestro/repl/gifthub/auth/service/NaverService.java, src/main/java/org/swmaestro/repl/gifthub/vouchers/service/VoucherSaveService.java
구글 로그인 시 500에러 발생
- `findByPlatformAndPlatformIdAndDeletedAtIsNull` 로 변경 (기존 작업에서 누락됐었음)
- notification message 수정 및 중복 저장 제거
`notification message` 수정을 위한 이슈 만들기에는 너무 사소한 작업 같아서 한 브랜치에 작업하였습니다. 양해 부탁드립니다.
=> Change to read method to handle google sign-in 500 error

src/main/java/org/swmaestro/repl/gifthub/notifications/controller/NotificationController.java, src/main/java/org/swmaestro/repl/gifthub/notifications/entity/Notification.java, src/main/java/org/swmaestro/repl/gifthub/notifications/repository/NotificationRepository.java, src/main/java/org/swmaestro/repl/gifthub/notifications/service/NotificationService.java, src/main/java/org/swmaestro/repl/gifthub/notifications/service/ScheduledTasks.java, src/main/java/org/swmaestro/repl/gifthub/vouchers/dto/VoucherReadResponseDto.java, src/main/java/org/swmaestro/repl/gifthub/vouchers/entity/Voucher.java, src/main/java/org/swmaestro/repl/gifthub/vouchers/service/VoucherService.java
- 알림 삭제 기능 구현 요청
- 삭제된 기프티콘 조회 기능 구현 요청
- 유효기간 0일 남은 알림인 경우의 알림 메세지 수정 요청
- 삭제된 기프티콘의 경우 바코드 값을 null 변경하여 구현
- 기프티콘 상세 조회 시 `is_accessible` 프로퍼티로 접근 가능 여부를 판단
=> Implement notification delete api and permit access deleted voucher with null barcode

.github/workflows/dev-cd.yml, .github/workflows/dev-ci.yml, .github/workflows/prod-cd.yml, .github/workflows/prod-ci.yml, .gitignore, build.gradle, src/main/java/org/swmaestro/repl/gifthub/config/FCMConfig.java, src/main/java/org/swmaestro/repl/gifthub/config/WebClientConfig.java, src/main/java/org/swmaestro/repl/gifthub/vouchers/controller/VoucherController.java, src/main/java/org/swmaestro/repl/gifthub/vouchers/dto/VoucherUpdateResponseDto.java, src/main/java/org/swmaestro/repl/gifthub/vouchers/entity/Voucher.java, src/main/java/org/swmaestro/repl/gifthub/vouchers/service/GptService.java, src/main/java/org/swmaestro/repl/gifthub/vouchers/service/SearchService.java, src/main/java/org/swmaestro/repl/gifthub/vouchers/service/StorageService.java, src/main/java/org/swmaestro/repl/gifthub/vouchers/service/VoucherSaveService.java, src/main/java/org/swmaestro/repl/gifthub/vouchers/service/VoucherService.java, src/test/java/org/swmaestro/repl/gifthub/vouchers/controller/VoucherControllerTest.java
기프티콘 자동 등록 요청 시, GPT 서버에 요청이 가기도 전에 `recvAddress(..) failed: Connection reset by peer` 에러가 발생하면서 끝나버림
1. `WebClient Config`로 분리하고 생성자 주입으로 사용되도록 개선
2. WebClient에서 다양한 설정으로 에러나지 않도록 함
- [참고](https://velog.io/@profoundsea25/recvAddress..-failed-Connection-reset-by-peer-%ED%98%B9%EC%9D%80-Connection-prematurely-closed-BEFORE-response-%EB%8C%80%EC%B2%98%ED%95%98%EA%B8%B0)
- 유휴 커넥션을 일정 주기로 제거한다.
- maxConnection을 늘린다.
- lifo, 즉, 나중에 반환된 커넥션을 재사용하도록 한다. 이는 커넥션의 재사용률을 높인다.
- retry를 설정한다.
완벽하게 해결된 것은 아니지만, 기존보다는 개선되었다고 생각합니다!
=> Detach and set up with WebClient Config
